"""Sprint 1c — Synchroniser aide_application.html avec la nouvelle terminologie."""
import re
from pathlib import Path

AIDE = Path(r"D:/Download/02-Apps-Web/Repo-github/App/suivi-de-projets/01_img_aide/aide_application.html")

# Mapping general : on parcourt les rules dans l'ordre.
# Ordre IMPORTANT : les regex specifiques avant les generiques.
RULES = [
    # ─── ETAPE 1 : Concepts importants ───
    (r"<strong>Configurations :</strong>",
     "<strong>Domaines :</strong>",
     "Concept Config -> Domaine"),
    (r"<strong>Profils :</strong>",
     "<strong>Projets :</strong>",
     "Concept Profil -> Projet"),
    (r"Au sein d'une configuration, créez des profils pour isoler les données",
     "Au sein d'un domaine, créez des projets pour isoler les données",
     "Concept au sein config"),
    (r"\(ex: par chef de projet, par utilisateur, par grand projet\.\.\.\)",
     "(ex: par chef de projet, par grand projet d'investissement, par machine d'atelier...)",
     "Ex profils"),

    # ─── ETAPE 2 : Permissions ───
    (r"<code class=\"highlight\">🔒 Autoriser dossiers \(Config X\)</code> \(où X est le numéro de la configuration active\)",
     '<code class="highlight">🔒 Autoriser dossiers (Domaine X)</code> (où X est le numéro du domaine actif)',
     "Bouton Autoriser ref"),
    (r"les dossiers ne sont pas définis pour la configuration active",
     "les dossiers ne sont pas définis pour le domaine actif",
     "Hint config active"),
    (r"Vous devrez potentiellement le faire pour chaque <strong>Configuration</strong> que vous utilisez\.",
     "Vous devrez potentiellement le faire pour chaque <strong>Domaine</strong> que vous utilisez.",
     "Chaque Config"),
    (r"💡 Les chemins des dossiers choisis sont visibles dans l'onglet <code>Configuration</code>\.",
     "💡 Les chemins des dossiers choisis sont visibles dans l'onglet <code>Réglages</code>.",
     "Onglet Config -> Reglages"),

    # ─── ETAPE 3 : Configurations & Profils ───
    (r"<!-- Étape 3: Configurations et Profils -->",
     "<!-- Étape 3: Domaines et Projets -->",
     "Comment etape 3"),
    (r"<h2>Configurations & Profils : Le Cœur de l'Organisation</h2>",
     "<h2>Domaines & Projets : Le Cœur de l'Organisation</h2>",
     "Titre etape 3"),
    (r"<h3>1\. Configurations \(Onglet <code>Tableau de bord</code> / <code>Configuration</code>\)</h3>",
     '<h3>1. Domaines (Onglet <code>Tableau de bord</code> / <code>Réglages</code>)</h3>',
     "Sous-titre 1"),
    (r"Sélectionnez la configuration active avec le menu déroulant <code class=\"highlight\">Configuration :</code>",
     'Sélectionnez le domaine actif avec le menu déroulant <code class="highlight">Domaine :</code>',
     "Selecteur config -> domaine"),
    (r"Chaque configuration a ses propres dossiers Backup/PJ et sa propre liste de profils\.",
     "Chaque domaine a ses propres dossiers Backup/PJ et sa propre liste de projets.",
     "Chaque config"),
    (r"<strong>Exemples :</strong> \"Projets Investissements\", \"Suivi Qualité Usine\", \"Maintenance Bâtiment\", \"Projets Perso\"\.",
     '<strong>Exemples :</strong> "Investissements 2026", "Atelier de Production", "Maintenance Bâtiment", "Projets Perso".',
     "Exemples domaines"),
    (r"Vous pouvez <span class=\"highlight\">nommer</span> chaque configuration dans l'onglet <code>Configuration</code> pour plus de clarté\.",
     'Vous pouvez <span class="highlight">nommer</span> chaque domaine dans l\'onglet <code>Réglages</code> pour plus de clarté.',
     "Nommer config"),
    (r"<!-- AJOUT clarification sauvegarde config -->",
     "<!-- AJOUT clarification sauvegarde domaine -->",
     "Comment"),
    (r"Les sauvegardes créées sont stockées dans le dossier Backup de la configuration active et sont spécifiques à celle-ci",
     "Les sauvegardes créées sont stockées dans le dossier Backup du domaine actif et sont spécifiques à celui-ci",
     "Sauvegarde config -> domaine"),
    (r"\(leur nom de fichier inclut l'identifiant de la configuration, ex: <code>C1_\.\.\.</code>\)",
     "(leur nom de fichier inclut l'identifiant du domaine, ex: <code>C1_...</code> où C signifie historiquement \"Config\" mais représente votre Domaine actuel)",
     "Identifiant fichier"),
    (r"<h3>2\. Profils \(Onglet <code>Tableau de bord</code>\)</h3>",
     "<h3>2. Projets (Onglet <code>Tableau de bord</code>)</h3>",
     "Sous-titre 2 profil"),
    (r"Au sein de la configuration active, vous pouvez créer <span class=\"highlight\">plusieurs profils</span>\.",
     'Au sein du domaine actif, vous pouvez créer <span class="highlight">plusieurs projets</span>.',
     "Au sein config"),
    (r"Sélectionnez le profil actif avec le menu déroulant <code class=\"highlight\">Profil :</code>\.",
     'Sélectionnez le projet actif avec le menu déroulant <code class="highlight">Projet :</code>.',
     "Selecteur profil"),
    (r"<!-- AJOUT clarification sauvegarde profil -->",
     "<!-- AJOUT clarification sauvegarde projet -->",
     "Comment 2"),
    (r"Chaque profil contient son propre ensemble de Projets, d'Actions, et ses propres",
     "Chaque projet contient son propre ensemble de Thématiques, d'Actions, et ses propres",
     "Chaque profil contient"),
    (r"complètement isolé des autres profils \(leur nom de fichier inclut aussi l'identifiant du profil, ex: <code>\.\.\._profilId_\.\.\.</code>\)\.",
     "complètement isolé des autres projets (leur nom de fichier inclut aussi l'identifiant du projet, ex: <code>..._profilId_...</code>).",
     "Isolation profils"),
    (r"<strong>Exemples :</strong> \"ChefProjet_Dupont\", \"Fournisseur_XYZ\", \"GrandProjet_Alpha\", \"Utilisateur_Martin\"\.",
     '<strong>Exemples :</strong> "Investissement Ligne Alpha", "Machine PROD-12", "Refonte ERP 2026", "Audit Qualité Q3".',
     "Exemples projets"),
    (r"Utilisez les boutons <code class=\"highlight\">Créer Profil</code>, <code class=\"highlight\">Supprimer Profil</code> et <code class=\"highlight\">Renommer</code> \(à côté du select Profil\) pour les gérer\.",
     'Utilisez les boutons <code class="highlight">Créer Projet</code>, <code class="highlight">Supprimer Projet</code> et <code class="highlight">Renommer</code> (à côté du select Projet) pour les gérer.',
     "Boutons gestion profil"),
    (r"Pensez d'abord à la <strong>Configuration</strong> \(le grand contexte\), puis au <strong>Profil</strong> \(le sous-ensemble spécifique\) que vous voulez utiliser\.",
     "Pensez d'abord au <strong>Domaine</strong> (le grand contexte), puis au <strong>Projet</strong> (le sous-ensemble spécifique) que vous voulez utiliser.",
     "Conseil pensez"),
    (r"alt=\"Menus Config/Profil\"",
     'alt="Menus Domaine/Projet"',
     "Alt image"),

    # ─── ETAPE 4 : Tableau de bord ───
    (r"Menus déroulants <code class=\"highlight\">Configuration :</code> et <code class=\"highlight\">Profil :</code> pour choisir votre contexte de travail\.",
     'Menus déroulants <code class="highlight">Domaine :</code> et <code class="highlight">Projet :</code> pour choisir votre contexte de travail.',
     "Menus deroulants TB"),
    (r"Bouton <code class=\"highlight\">Sauvegarder</code> : Crée une sauvegarde manuelle immédiate du profil actif\.",
     'Bouton <code class="highlight">Sauvegarder</code> : Crée une sauvegarde manuelle immédiate du projet actif.',
     "Bouton sauvegarder TB"),
    (r"Boutons <code class=\"highlight\">Créer Profil</code> / <code class=\"highlight\">Supprimer Profil</code> / <code class=\"highlight\">Renommer</code> : Gèrent les profils de la configuration active\.",
     'Boutons <code class="highlight">Créer Projet</code> / <code class="highlight">Supprimer Projet</code> / <code class="highlight">Renommer</code> : Gèrent les projets du domaine actif.',
     "Boutons gestion TB"),
    (r"Liste les sauvegardes \(\.json\) existantes pour le profil actif",
     "Liste les sauvegardes (.json) existantes pour le projet actif",
     "Liste sauvegardes"),
    (r"Ce menu affiche <span class=\"highlight\">uniquement</span> les fichiers de sauvegarde qui correspondent à la <strong>Configuration ET au Profil</strong> actuellement sélectionnés\.",
     'Ce menu affiche <span class="highlight">uniquement</span> les fichiers de sauvegarde qui correspondent au <strong>Domaine ET au Projet</strong> actuellement sélectionnés.',
     "Filtre sauvegardes"),
    (r"Restaure l'état de l'application \(projets, actions, journal\.\.\.\) à partir de la sauvegarde sélectionnée\. <strong class=\"highlight\">IMPORTANT :</strong> Après avoir changé de Config ou de Profil, ce bouton clignotera",
     "Restaure l'état de l'application (thématiques, actions, journal...) à partir de la sauvegarde sélectionnée. <strong class=\"highlight\">IMPORTANT :</strong> Après avoir changé de Domaine ou de Projet, ce bouton clignotera",
     "Bouton Charger"),
    (r"<strong>Indicateurs Clés \(Stats\) :</strong> Nombre de projets actifs, actions en cours, en retard, terminées\.",
     "<strong>Indicateurs Clés (Stats) :</strong> Nombre de thématiques en cours, actions en cours, en retard, terminées.",
     "Indicateurs cles"),
    (r"<strong>Statistiques par Projet :</strong> Un tableau récapitulatif du nombre d'actions par statut pour chaque projet du profil actif\.",
     "<strong>Statistiques par Thématique :</strong> Un tableau récapitulatif du nombre d'actions par statut pour chaque thématique du projet actif.",
     "Stats par projet"),
    (r"Affiche l'historique récent des <span class=\"highlight\">créations, modifications et suppressions</span> de projets et d'actions pour le profil actif\.",
     'Affiche l\'historique récent des <span class="highlight">créations, modifications et suppressions</span> de thématiques et d\'actions pour le projet actif.',
     "Journal historique"),
    (r"l'utilisateur \(défini dans l'onglet Configuration\)",
     "l'utilisateur (défini dans l'onglet Réglages)",
     "Onglet Config -> Reglages bis"),
    (r"Possibilité de <code class=\"highlight\">Vider le journal</code> \(action irréversible pour ce profil\)\.",
     'Possibilité de <code class="highlight">Vider le journal</code> (action irréversible pour ce projet).',
     "Vider journal"),

    # ─── ETAPE 5 : Créer un Projet (devient Thématique) ───
    (r"<!-- Étape 5: Créer un Projet -->",
     "<!-- Étape 5: Créer une Thématique -->",
     "Comment etape 5"),
    (r"<h2>Créer votre Premier Projet</h2>",
     "<h2>Créer votre Première Thématique</h2>",
     "Titre etape 5"),
    (r"Les actions doivent être rattachées à un projet\. Commençons par en créer un\.",
     "Les actions doivent être rattachées à une thématique. Commençons par en créer une.",
     "Intro etape 5"),
    (r"Assurez-vous d'être dans la bonne <strong>Configuration</strong> et le bon <strong>Profil</strong> \(via le Tableau de bord\)\.",
     "Assurez-vous d'être dans le bon <strong>Domaine</strong> et le bon <strong>Projet</strong> (via le Tableau de bord).",
     "Assurez-vous"),
    (r"Allez dans l'onglet <code class=\"highlight\">Projets</code>\.",
     'Allez dans l\'onglet <code class="highlight">Thématiques</code>.',
     "Onglet Projets"),
    (r"Cliquez sur le bouton <code class=\"highlight\">➕ Ajouter un projet</code>\. Un formulaire apparaît\.",
     'Cliquez sur le bouton <code class="highlight">➕ Ajouter une thématique</code>. Un formulaire apparaît.',
     "Bouton ajouter projet"),
    (r"<strong>Nom du projet :</strong> Nom descriptif \(ex: \"Amélioration Ligne Prod 3\"\)\.",
     '<strong>Nom de la thématique :</strong> Nom descriptif (ex: "Process", "Maintenance préventive", "Outillage", "IHM").',
     "Nom projet"),
    (r"<strong>Préfixe :</strong> 2 à 4 lettres/chiffres pour l'identifiant unique \(ex: ALP3, INV24\)\.",
     "<strong>Préfixe :</strong> 2 à 4 lettres/chiffres pour l'identifiant unique (ex: PROC, MAINT, OUTI, IHM).",
     "Prefixe"),
    (r"<strong>Client/Fournisseur :</strong> Entité liée au projet\.",
     "<strong>Client/Fournisseur :</strong> Entité liée à la thématique.",
     "Client/Fournisseur"),
    (r"<strong>Statut :</strong> État actuel du projet \(Actif, Terminé\.\.\.\)\.",
     "<strong>Statut :</strong> État actuel de la thématique (Actif, Terminé...).",
     "Statut projet"),
    (r"Le projet apparaît maintenant dans la liste\. Chaque projet aura un numéro unique basé sur le préfixe et un compteur \(ex: <code>ALP3-001</code>\)\.",
     "La thématique apparaît maintenant dans la liste. Chaque thématique aura un numéro unique basé sur le préfixe et un compteur (ex: <code>PROC-001</code>).",
     "Numero projet"),
    (r"💡 Vous pouvez <strong>Modifier</strong> \(✏️\) ou <strong>Supprimer</strong> \(🗑️\) un projet via les icônes dans la liste\.",
     "💡 Vous pouvez <strong>Modifier</strong> (✏️) ou <strong>Supprimer</strong> (🗑️) une thématique via les icônes dans la liste.",
     "Modifier projet"),
    (r"alt=\"Ajout de projet\"",
     'alt="Ajout de thématique"',
     "Alt image projet"),

    # ─── ETAPE 6 : Créer une Action ───
    (r"<h2>Ajouter des Actions à un Projet</h2>",
     "<h2>Ajouter des Actions à une Thématique</h2>",
     "Titre etape 6"),
    (r"Maintenant que vous avez un projet, vous pouvez y ajouter des actions spécifiques\.",
     "Maintenant que vous avez une thématique, vous pouvez y ajouter des actions spécifiques.",
     "Intro 6"),
    (r"<strong>Projet associé :</strong> <span class=\"highlight\">Sélectionnez le projet</span> créé précédemment dans la liste déroulante\.",
     '<strong>Thématique associée :</strong> <span class="highlight">Sélectionnez la thématique</span> créée précédemment dans la liste déroulante.',
     "Projet associe"),
    (r"<strong>Thématique :</strong> Catégorie \(optionnel, ex: Mécanique, Elec, Software, Doc\.\.\.\)\.",
     "<strong>Tags :</strong> Mots-clés transverses pour filtrer (optionnel, ex: HMI, IT, Software, Mécanique, Doc...).",
     "Champ thematique -> Tags"),
    (r"Vous pouvez ajouter jusqu'à 5 fichiers par action\.",
     "Vous pouvez ajouter jusqu'à 10 fichiers par action (sélection multiple + glisser-déposer supportés).",
     "PJ max"),
    (r"L'action apparaît dans le tableau\. Elle aura un numéro unique lié au projet \(ex: <code>ALP3-001-001</code>\)\.",
     "L'action apparaît dans le tableau. Elle aura un numéro unique lié à la thématique (ex: <code>PROC-001-001</code>).",
     "Numero action"),
    (r"💡 Les PJs sont physiquement copiées dans le dossier \"PJ\" de la configuration active lorsque vous enregistrez l'action\.",
     "💡 Les PJs sont physiquement copiées dans le dossier \"PJ\" du domaine actif lorsque vous enregistrez l'action.",
     "PJ copiees"),

    # ─── ETAPE 7 : Gérer Actions et PJs ───
    (r"Par <span class=\"highlight\">Projet</span> \(menu déroulant\)\.",
     'Par <span class="highlight">Thématique</span> (menu déroulant).',
     "Filtre projet -> thematique"),

    # ─── ETAPE 8 : L'Onglet Configuration ───
    (r"<!-- Étape 8: L'Onglet Configuration -->",
     "<!-- Étape 8: L'Onglet Réglages -->",
     "Comment etape 8"),
    (r"<h2>L'Onglet Configuration : Paramétrage Avancé</h2>",
     "<h2>L'Onglet Réglages : Paramétrage Avancé</h2>",
     "Titre etape 8"),
    (r"<strong>Gestion des Configurations \(1-10\) :</strong>",
     "<strong>Gestion des Domaines (1-10) :</strong>",
     "Gestion configs"),
    (r"Permet de <span class=\"highlight\">Nommer</span> chaque configuration pour la reconnaître facilement \(ex: \"Projets R&D\", \"Support Client\"\)\.",
     'Permet de <span class="highlight">Nommer</span> chaque domaine pour le reconnaître facilement (ex: "R&D", "Production Ligne 2", "Atelier Sud").',
     "Nommer chaque config"),
    (r"Boutons <code class=\"highlight\">Redéfinir</code> pour \(re\)définir les dossiers <span class=\"highlight\">Backup</span> et <span class=\"highlight\">PJ</span> pour chaque configuration individuelle\.",
     'Boutons <code class="highlight">Redéfinir</code> pour (re)définir les dossiers <span class="highlight">Backup</span> et <span class="highlight">PJ</span> pour chaque domaine individuel.',
     "Redefinir dossiers"),
    (r"<strong>Sauvegarder / Restaurer \(Profil Actif\) :</strong>",
     "<strong>Sauvegarder / Restaurer (Projet Actif) :</strong>",
     "Section sauve"),
    (r"<code class=\"highlight\">Sauvegarder Profil Actif</code> : Crée une sauvegarde manuelle du profil actuellement sélectionné dans la configuration active\.",
     '<code class="highlight">Sauvegarder Projet Actif</code> : Crée une sauvegarde manuelle du projet actuellement sélectionné dans le domaine actif.',
     "Sauve profil actif"),
    (r"Permet de charger des données \(projets, actions\) à partir d'un fichier <code>\.json</code> externe \(attention, cela écrase les données actuelles du profil !\)\.",
     "Permet de charger des données (thématiques, actions) à partir d'un fichier <code>.json</code> externe (attention, cela écrase les données actuelles du projet !).",
     "Restaurer fichier"),
    (r"<strong>Fonctions avancées Profils :</strong> \(Non implémentées pour l'instant\) Export/Import/Réparation groupés de profils\.",
     "<strong>Fonctions avancées Projets :</strong> (Non implémentées pour l'instant) Export/Import/Réparation groupés de projets.",
     "Fonctions avancees"),
    (r"<code class=\"highlight\">Recalculer Numéros Actions</code> : Réorganise les numéros séquentiels des actions \(le dernier chiffre après le projet, ex: 001, 002\.\.\.\) pour qu'ils soient consécutifs au sein de chaque projet\.",
     '<code class="highlight">Recalculer Numéros Actions</code> : Réorganise les numéros séquentiels des actions (le dernier chiffre après la thématique, ex: 001, 002...) pour qu\'ils soient consécutifs au sein de chaque thématique.',
     "Recalculer numeros"),
    (r"<code class=\"highlight\">Réinitialiser Compteur Projets</code> : \(⚠️ Dangereux\) Change le numéro qui sera attribué au PROCHAIN projet créé\.",
     '<code class="highlight">Réinitialiser Compteur Thématiques</code> : (⚠️ Dangereux) Change le numéro qui sera attribué à la PROCHAINE thématique créée.',
     "Reinit compteur"),
    (r"alt=\"Onglet configuration\"",
     'alt="Onglet Réglages"',
     "Alt onglet config"),

    # ─── ETAPE 9 : Verrouillage ───
    (r"Éviter que deux personnes modifient les mêmes données \(le même profil dans la même configuration\) en même temps",
     "Éviter que deux personnes modifient les mêmes données (le même projet dans le même domaine) en même temps",
     "Objectif verrou"),
    (r"Quand vous chargez un profil \(via le bouton <code>Charger</code> du Tableau de Bord\)",
     "Quand vous chargez un projet (via le bouton <code>Charger</code> du Tableau de Bord)",
     "Chargez profil"),
    (r"dans le dossier Backup de la configuration active",
     "dans le dossier Backup du domaine actif",
     "Dossier backup config active"),
    (r"\"Vous éditez: Profil \[\.\.\.\]\"",
     '"Vous éditez: Projet [...]"',
     "Banner edite"),
    (r"Vous pouvez modifier les projets et les actions normalement\.",
     "Vous pouvez modifier les thématiques et les actions normalement.",
     "Modifier projets actions"),
    (r"Si le profil est déjà verrouillé par quelqu'un d'autre",
     "Si le projet est déjà verrouillé par quelqu'un d'autre",
     "Profil verrouille autre"),
    (r"\"Consultation: Profil \[\.\.\.\] - Verrouillé\.\"",
     '"Consultation: Projet [...] - Verrouillé."',
     "Banner consultation"),
    (r"vous pouvez consulter, filtrer, exporter, mais pas ajouter, modifier ou supprimer de projets/actions\. L'onglet Configuration reste utilisable\.",
     "vous pouvez consulter, filtrer, exporter, mais pas ajouter, modifier ou supprimer de thématiques/actions. L'onglet Réglages reste utilisable.",
     "Mode lecture seule"),

    # ─── ETAPE 10 : Tips & Conclusion ───
    (r"<strong>Nommez bien vos Configurations et Profils :</strong> Cela rend la navigation beaucoup plus simple\. Utilisez la fonction \"Nommer\" dans l'onglet <code>Configuration</code>\.",
     '<strong>Nommez bien vos Domaines et Projets :</strong> Cela rend la navigation beaucoup plus simple. Utilisez la fonction "Nommer" dans l\'onglet <code>Réglages</code>.',
     "Tip nommer"),
    (r"<strong>Sauvegardes Régulières :</strong> Même si l'auto-sauvegarde existe, n'hésitez pas à faire une sauvegarde manuelle \(via le Tableau de Bord ou Config\) avant une opération importante",
     "<strong>Sauvegardes Régulières :</strong> Même si l'auto-sauvegarde existe, n'hésitez pas à faire une sauvegarde manuelle (via le Tableau de Bord ou Réglages) avant une opération importante",
     "Tip sauvegardes"),
    (r"Les filtres par statut, projet et texte sont vos meilleurs alliés pour retrouver une information\.",
     "Les filtres par statut, thématique et texte sont vos meilleurs alliés pour retrouver une information.",
     "Tip filtres"),
    (r"Son potentiel réside dans sa capacité à s'adapter à différents contextes grâce aux Configurations et Profils\.",
     "Son potentiel réside dans sa capacité à s'adapter à différents contextes grâce aux Domaines et Projets.",
     "Conclusion"),
]


def main():
    s = AIDE.read_text(encoding="utf-8")
    orig_len = len(s)
    print(f"== Sprint 1c AIDE on {AIDE.name} ({orig_len} chars) ==\n")
    total_replacements = 0
    for pattern, repl, label in RULES:
        new, n = re.subn(pattern, repl, s, flags=re.MULTILINE | re.DOTALL)
        marker = "OK" if n > 0 else "--"
        print(f"  [{marker}] {label}: {n}")
        if n > 0:
            s = new
            total_replacements += n
    AIDE.write_text(s, encoding="utf-8")
    print(f"\n== {total_replacements} remplacements, taille: {orig_len} -> {len(s)} ==")


if __name__ == "__main__":
    main()
